---
- name: Playbook to create custom EE
  hosts: all
  gather_facts: false
  collections:
    - redhat_cop.controller_configuration
  tasks:
    - name: create execution environment definition file
      ansible.builtin.template:
        src: ee_controller.yaml.j2
        dest: "/tmp/ee_controller.yaml"
        mode: '0644'

    - name: Include tempalted variables
      ansible.builtin.include_vars:
        file: "/tmp/ee_controller.yaml"

    - name: Include tempalted variables
      debug:
        var: controller_execution_environments
...
